// Code generated by Slice Machine. DO NOT EDIT.

import Image from './Image';
import List from './List';
import Text from './Text';
import Texts from './Texts';

export {
	Image,
	List,
	Text,
	Texts,
};

export const components = {
	image: Image,
	list: List,
	text: Text,
	texts: Texts,
};
